// Type
import { Page } from "../type/page";

export const PAGE_PATH: Record<Page, string> = {
  Dashboard: 'dashboard',
  ลูกค้า: 'customers',
  ใบประเมิน: 'assessments',
  ฟอร์ม: 'forms',
  ภาคสนาม: 'field-operations',
  ใบเสนอราคา: 'quotations',
  ใบแจ้งหนี้: 'billing',
  'ใบกำกับภาษี/ใบเสร็จรับเงิน': 'receipts',
  หมวดหมู่: 'categories',
  'สินค้า/บริการ': 'inventory',
  แพ็กเกจ: 'packages',
  คลังสินค้า: 'warehouse',
  ผู้จัดจำหน่าย: 'suppliers',
  รับเข้า: 'goods-receipt',
  'เบิกสินค้า/อุปกรณ์ และค่าใช้จ่าย': 'withdrawals',
  โอนย้าย: 'transfers',
  'ปรับปรุง Stock': 'stock-adjustment',
  คืนสินค้า: 'returns',
  เบิกสินค้าคืนผู้จำหน่าย: 'return-to-supplier',
  ผู้ใช้งาน: 'users',
  จัดการบทบาท: 'roles',
  การแจ้งเตือน: 'notifications',
  รายงาน: 'reports',
  'ยอดขาย(รายเดือน)': 'reports/monthly-sales',
  'สรุปยอดขาย(รายเดือน)': 'reports/sales-summary',
  'รายงานรายได้ (รายเดือน)': 'reports/total-income',
  'รายได้ออกใบกำกับ(รายเดือน)': 'reports/tax-invoice-income',
  ค่าใช้จ่ายทางอ้อม: 'reports/indirect-expenses',
  บัญชีเงินสดรายวัน: 'reports/daily-cash',
  ค่าใช้จ่ายทางตรง: 'reports/direct-expenses',
};
