name: mrgreenpest-uat
services:
  # React Frontend Application (Production)
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      args:
        - API_BASE_URL=https://mrgreenpest.knacx.uat/api
    image: mrgreenpest-uat:latest
    container_name: mrgreenpest-uat
    ports:
      - '4500:80'
    restart: unless-stopped
    networks:
      - mrgreenpest-uat-network

networks:
  mrgreenpest-uat-network:
    driver: bridge
