// FIX: Import all types from the central 'types.ts' file and define only constants and mock data.
import {
  Status,
  UserRole,
  User,
  Customer,
  Product,
  Assessment,
  FieldJob,
  Quotation,
  Invoice,
  Receipt,
  Warehouse,
  GoodsReceipt,
  Supplier,
  Withdrawal,
  Transfer,
  StockAdjustment,
  ProductReturn,
  Contract,
  UserWallet,
  ReturnToSupplier,
} from '@/src/libs/common/interface/entity/app.interface';
import {
  CurrencyDollarIcon,
  DocumentTextIcon,
  ShieldCheckIcon,
  NewDashboardIcon,
  NewCustomerIcon,
  NewAssessmentIcon,
  NewFieldOpsIcon,
  NewAccountingIcon,
  NewWarehouseIcon,
  NewUsersIcon,
  NewReportIcon,
  PackageIcon,
  BookOpenIcon,
  BellIcon,
} from './assets/icons/Icons';
import { NavigationItem } from '@/src/libs/common/type/nav';

// FIX: Add and export date formatting utility functions.
export const formatThaiDate = (isoString: string | undefined): string => {
  if (!isoString) return '-';
  const date = new Date(isoString);
  return date.toLocaleDateString('th-TH', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
};

export const formatThaiDateTime = (isoString: string | undefined): string => {
  if (!isoString) return '-';
  const date = new Date(isoString);
  return (
    date.toLocaleString('th-TH', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    }) + ' น.'
  );
};

export const NAVIGATION_ITEMS: NavigationItem[] = [
  { type: 'link', name: 'Dashboard', icon: NewDashboardIcon },
  { type: 'link', name: 'ลูกค้า', icon: NewCustomerIcon },
  { type: 'link', name: 'ฟอร์ม', icon: DocumentTextIcon },
  // { type: 'link', name: 'ใบประเมิน', icon: NewAssessmentIcon },
  // { type: 'link', name: 'ภาคสนาม', icon: NewFieldOpsIcon },
  {
    type: 'group',
    name: 'การเงินและบัญชี',
    icon: NewAccountingIcon,
    subItems: [
      { name: 'ใบเสนอราคา', icon: DocumentTextIcon },
      { name: 'ใบแจ้งหนี้', icon: CurrencyDollarIcon },
      { name: 'ใบกำกับภาษี/ใบเสร็จรับเงิน', icon: ShieldCheckIcon },
    ],
  },
  {
    type: 'group',
    name: 'คลังสินค้า',
    icon: NewWarehouseIcon,
    subItems: [
      { name: 'คลังสินค้า', icon: NewWarehouseIcon },
      { name: 'รับเข้า', icon: NewWarehouseIcon },
      { name: 'โอนย้าย', icon: NewWarehouseIcon },
      { name: 'ปรับปรุง Stock', icon: NewWarehouseIcon },
      { name: 'เบิกสินค้าคืนผู้จำหน่าย', icon: NewWarehouseIcon },
    ],
  },
  {
    type: 'group',
    name: 'จัดการสินค้าภายใน',
    icon: NewWarehouseIcon,
    subItems: [
      { name: 'เบิกสินค้า/อุปกรณ์ และค่าใช้จ่าย', icon: NewWarehouseIcon },
      { name: 'คืนสินค้า', icon: NewWarehouseIcon },
    ],
  },
  {
    type: 'group',
    name: 'ข้อมูลสินค้าและคู่ค้า',
    icon: PackageIcon,
    subItems: [
      { name: 'สินค้า/บริการ', icon: PackageIcon },
      { name: 'แพ็กเกจ', icon: PackageIcon },
      { name: 'หมวดหมู่', icon: BookOpenIcon },
      { name: 'ผู้จัดจำหน่าย', icon: NewUsersIcon },
    ],
  },
  {
    type: 'group',
    name: 'การตั้งค่าระบบ',
    icon: NewUsersIcon,
    subItems: [{ name: 'ผู้ใช้งาน' }, { name: 'จัดการบทบาท' }],
  },
  {
    type: 'group',
    name: 'รายงาน',
    icon: NewReportIcon,
    subItems: [
      { name: 'รายงานรายได้ (รายเดือน)' },
      { name: 'รายได้ออกใบกำกับ(รายเดือน)' },
      { name: 'ค่าใช้จ่ายทางอ้อม' },
      { name: 'บัญชีเงินสดรายวัน' },
      { name: 'ค่าใช้จ่ายทางตรง' },
      { name: 'ยอดขาย(รายเดือน)' },
      { name: 'สรุปยอดขาย(รายเดือน)' },
    ],
  },
  { type: 'link', name: 'การแจ้งเตือน', icon: BellIcon },
];

export const MOCK_USERS: User[] = [
  {
    id: 'user-1',
    nationalId: '1234567890121',
    name: 'อดัม',
    nickname: 'ดัม',
    email: 'adam.tech@mrgreenpest.com',
    role: UserRole.Technician,
    avatarUrl: 'https://picsum.photos/seed/user1/100/100',
    phone: '081-123-4567',
    creditLimit: 5000,
  },
  {
    id: 'user-2',
    nationalId: '1234567890122',
    name: 'อลิซ',
    nickname: 'ลิซ',
    email: 'alice@mrgreenpest.com',
    role: UserRole.Sales,
    avatarUrl: 'https://picsum.photos/seed/user2/100/100',
    phone: '082-234-5678',
  },
  {
    id: 'user-3',
    nationalId: '1234567890123',
    name: 'บ็อบ',
    nickname: 'บ็อบ',
    email: 'bob@mrgreenpest.com',
    role: UserRole.Accounting,
    avatarUrl: 'https://picsum.photos/seed/user3/100/100',
    phone: '083-345-6789',
  },
  {
    id: 'user-4',
    nationalId: '1234567890124',
    name: 'ชาร์ลี',
    nickname: 'ชาร์ลี',
    role: UserRole.Warehouse,
    avatarUrl: 'https://picsum.photos/seed/user4/100/100',
    phone: '084-456-7890',
  },
  {
    id: 'user-5',
    nationalId: '1234567890125',
    name: 'ไดอาน่า',
    nickname: 'ดีดี้',
    email: 'diana@mrgreenpest.com',
    role: UserRole.Dispatcher,
    avatarUrl: 'https://picsum.photos/seed/user5/100/100',
    phone: '085-567-8901',
  },
  {
    id: 'user-6',
    nationalId: '1234567890126',
    name: 'อีธาน',
    nickname: 'อีธาน',
    email: 'ethan@mrgreenpest.com',
    role: UserRole.Technician,
    avatarUrl: 'https://picsum.photos/seed/user6/100/100',
    phone: '086-678-9012',
    creditLimit: 3000,
  },
  {
    id: 'user-7',
    nationalId: '1234567890127',
    name: 'ฟิโอน่า',
    nickname: 'ฟี',
    email: 'fiona@mrgreenpest.com',
    role: UserRole.Technician,
    avatarUrl: 'https://picsum.photos/seed/user7/100/100',
    phone: '087-789-0123',
    creditLimit: 3000,
  },
  {
    id: 'user-8',
    nationalId: '1234567890128',
    name: 'จอร์จ',
    nickname: 'จอร์จ',
    email: 'george@mrgreenpest.com',
    role: UserRole.Technician,
    avatarUrl: 'https://picsum.photos/seed/user8/100/100',
    phone: '088-123-4567',
  },
  {
    id: 'user-9',
    nationalId: '1234567890129',
    name: 'แฮร์รี่',
    nickname: 'แฮร์รี่',
    email: 'harry@mrgreenpest.com',
    role: UserRole.Technician,
    avatarUrl: 'https://picsum.photos/seed/user9/100/100',
    phone: '089-234-5678',
  },
  {
    id: 'user-10',
    nationalId: '1234567890130',
    name: 'ไอวี่',
    nickname: 'ไอวี่',
    email: 'ivy@mrgreenpest.com',
    role: UserRole.Technician,
    avatarUrl: 'https://picsum.photos/seed/user10/100/100',
    phone: '090-345-6789',
  },
  {
    id: 'user-11',
    nationalId: '1234567890131',
    name: 'แจ็ค',
    nickname: 'แจ็ค',
    email: 'jack@mrgreenpest.com',
    role: UserRole.Technician,
    avatarUrl: 'https://picsum.photos/seed/user11/100/100',
    phone: '091-456-7890',
  },
  {
    id: 'user-12',
    nationalId: '1234567890132',
    name: 'เควิน',
    nickname: 'เค',
    email: 'kevin@mrgreenpest.com',
    role: UserRole.Technician,
    avatarUrl: 'https://picsum.photos/seed/user12/100/100',
    phone: '092-567-8901',
  },
  {
    id: 'user-13',
    nationalId: '1234567890133',
    name: 'เลียม',
    nickname: 'เลียม',
    email: 'liam@mrgreenpest.com',
    role: UserRole.Technician,
    avatarUrl: 'https://picsum.photos/seed/user13/100/100',
    phone: '093-678-9012',
  },
  {
    id: 'user-14',
    nationalId: '1234567890134',
    name: 'โมนา',
    nickname: 'โม',
    email: 'mona@mrgreenpest.com',
    role: UserRole.Technician,
    avatarUrl: 'https://picsum.photos/seed/user14/100/100',
    phone: '094-789-0123',
  },
  {
    id: 'user-15',
    nationalId: '1234567890135',
    name: 'นีนา',
    nickname: 'นีน่า',
    email: 'nina@mrgreenpest.com',
    role: UserRole.Technician,
    avatarUrl: 'https://picsum.photos/seed/user15/100/100',
    phone: '095-890-1234',
  },
  {
    id: 'user-16',
    nationalId: '1234567890136',
    name: 'ออสการ์',
    nickname: 'ออส',
    email: 'oscar@mrgreenpest.com',
    role: UserRole.Technician,
    avatarUrl: 'https://picsum.photos/seed/user16/100/100',
    phone: '096-901-2345',
  },
  {
    id: 'user-17',
    nationalId: '1234567890137',
    name: 'พอล',
    nickname: 'พอล',
    email: 'paul@mrgreenpest.com',
    role: UserRole.Technician,
    avatarUrl: 'https://picsum.photos/seed/user17/100/100',
    phone: '097-012-3456',
  },
  {
    id: 'user-18',
    nationalId: '1234567890138',
    name: 'แอดมิน',
    nickname: 'แอดมิน',
    email: 'admin@mrgreenpest.com',
    role: UserRole.Admin,
    avatarUrl: 'https://picsum.photos/seed/user18/100/100',
    phone: '080-000-1111',
  },
];

export const MOCK_USER_WALLETS: UserWallet[] = MOCK_USERS.map((user) => {
  if (user.id === 'user-1') {
    return {
      userId: user.id,
      transactions: [
        {
          id: 'txn-1',
          date: '2023-09-22T10:00:00.000Z',
          description: 'รับเงินเบิกจากใบเบิกเลขที่ SR670001',
          type: 'รายรับ',
          amount: 420,
          referenceId: 'SR670001',
        },
        {
          id: 'txn-2',
          date: '2023-09-22T12:30:00.000Z',
          description: 'ค่าอาหารกลางวัน',
          type: 'รายจ่าย',
          amount: 150,
        },
      ],
    };
  }
  return {
    userId: user.id,
    transactions: [],
  };
});

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: 'C0001',
    name: 'ห้างแกรนด์เซ็นทรัล',
    type: 'นิติบุคคล',
    contactPerson: 'คุณสมศักดิ์',
    contactPersonPhone: '02-111-2222',
    email: 'john.doe@central.com',
    phone: '02-111-2222',
    address: {
      street: '999',
      road: 'พระราม 1',
      subdistrict: 'ปทุมวัน',
      district: 'ปทุมวัน',
      province: 'กรุงเทพมหานคร',
      postalcode: '10330',
      country: 'ประเทศไทย',
      zone: 'A1',
      group: 'G1',
      roadLine: '1',
      sequence: '1',
    },
    taxId: '0105558000111',
    createdAt: '2023-01-15',
    contractUntil: '2024-12-31',
    googleMapLink: 'https://maps.app.goo.gl/j5pZk9wQ8yL3x7rF7',
  },
  {
    id: 'C0002',
    name: 'คุณสมชาย L.',
    nickname: 'ชาย',
    type: 'บุคคลธรรมดา',
    contactPerson: 'คุณสมชาย L.',
    gender: 'ชาย',
    email: 'somchai.l@example.com',
    phone: '088-888-8888',
    mobilePhone: '081-123-4567',
    address: {
      street: '123',
      road: 'สุขุมวิท',
      subdistrict: 'คลองเตย',
      district: 'คลองเตย',
      province: 'กรุงเทพมหานคร',
      postalcode: '10110',
      country: 'ประเทศไทย',
    },
    taxId: '',
    createdAt: '2023-03-20',
    contractUntil: '2024-08-15',
  },
  {
    id: 'C0003',
    name: 'ร้านกาแฟ Bake a Wish',
    type: 'นิติบุคคล',
    contactPerson: 'คุณเจน',
    contactPersonPhone: '02-333-4444',
    email: 'jane@bakeawish.co.th',
    phone: '02-333-4444',
    address: {
      street: 'สยามสแควร์วัน',
      subdistrict: 'ปทุมวัน',
      district: 'ปทุมวัน',
      province: 'กรุงเทพมหานคร',
      postalcode: '10330',
      country: 'ประเทศไทย',
    },
    taxId: '0105559000222',
    createdAt: '2023-05-10',
  },
  {
    id: 'C0004',
    name: 'คุณพลอย P.',
    nickname: 'พลอย',
    type: 'บุคคลธรรมดา',
    contactPerson: 'คุณพลอย P.',
    gender: 'หญิง',
    email: 'ploy.p@example.com',
    phone: '099-999-9999',
    mobilePhone: '098-765-4321',
    address: {
      street: '456',
      road: 'ลาดพร้าว',
      subdistrict: 'จตุจักร',
      district: 'จตุจักร',
      province: 'กรุงเทพมหานคร',
      postalcode: '10900',
      country: 'ประเทศไทย',
    },
    taxId: '',
    createdAt: '2023-08-01',
    contractUntil: '2024-07-20',
  },
  {
    id: 'C0005',
    name: 'บจก. กรีนมาร์ท',
    type: 'นิติบุคคล',
    contactPerson: 'คุณวัชระ',
    email: 'contact@greenmart.co.th',
    phone: '02-222-3333',
    address: {
      street: '12/3',
      road: 'พหลโยธิน',
      subdistrict: 'ลาดยาว',
      district: 'จตุจักร',
      province: 'กรุงเทพมหานคร',
      postalcode: '10900',
      country: 'ประเทศไทย',
    },
    taxId: '',
    createdAt: '2024-01-10',
  },
  {
    id: 'C0006',
    name: 'คอนโด ซิตี้วิว',
    type: 'นิติบุคคล',
    contactPerson: 'นิติบุคคลอาคารชุด',
    phone: '02-555-1111',
    address: {
      street: '88',
      road: 'เจริญกรุง',
      subdistrict: 'บางรัก',
      district: 'บางรัก',
      province: 'กรุงเทพมหานคร',
      postalcode: '10500',
      country: 'ประเทศไทย',
    },
    taxId: '',
    createdAt: '2024-02-18',
  },
  {
    id: 'C0007',
    name: 'คุณดล D.',
    nickname: 'ดล',
    type: 'บุคคลธรรมดา',
    contactPerson: 'คุณดล D.',
    phone: '081-777-8888',
    address: {
      street: '99/1',
      road: 'กาญจนาภิเษก',
      subdistrict: 'บางแค',
      district: 'บางแค',
      province: 'กรุงเทพมหานคร',
      postalcode: '10160',
      country: 'ประเทศไทย',
    },
    taxId: '',
    createdAt: '2024-03-22',
  },
  {
    id: 'C0008',
    name: 'ร้าน The Coffee Hub',
    type: 'นิติบุคคล',
    contactPerson: 'คุณธนชัย',
    phone: '02-333-2222',
    email: 'owner@coffeehub.co.th',
    address: {
      street: '15',
      road: 'ศรีนครินทร์',
      subdistrict: 'บางแก้ว',
      district: 'บางพลี',
      province: 'สมุทรปราการ',
      postalcode: '10540',
      country: 'ประเทศไทย',
    },
    taxId: '',
    createdAt: '2024-04-02',
  },
  {
    id: 'C0009',
    name: 'คุณมินตรา M.',
    nickname: 'มิน',
    type: 'บุคคลธรรมดา',
    contactPerson: 'คุณมินตรา M.',
    phone: '086-222-1111',
    address: {
      street: '45/6',
      road: 'นิมมานเหมินทร์',
      subdistrict: 'สุเทพ',
      district: 'เมืองเชียงใหม่',
      province: 'เชียงใหม่',
      postalcode: '50200',
      country: 'ประเทศไทย',
    },
    taxId: '',
    createdAt: '2024-05-09',
  },
  {
    id: 'C0010',
    name: 'โรงแรม ซีบรีซ',
    type: 'นิติบุคคล',
    contactPerson: 'ฝ่ายอาคาร',
    phone: '032-999-8888',
    address: {
      street: '101',
      road: 'เพชรเกษม',
      subdistrict: 'หัวหิน',
      district: 'หัวหิน',
      province: 'ประจวบคีรีขันธ์',
      postalcode: '77110',
      country: 'ประเทศไทย',
    },
    taxId: '',
    createdAt: '2024-06-15',
  },
];

export const MOCK_SUPPLIERS: Supplier[] = [
  {
    id: 'SP0001',
    name: 'บริษัท เคมีภัณฑ์ จำกัด',
    type: 'นิติบุคคล',
    taxId: '0105551234567',
    contactPerson: 'คุณวิชัย',
    phones: ['02-999-8888'],
    email: 'sales@chemisupply.co.th',
  },
  {
    id: 'SP0002',
    name: 'นายสมเกียรติ อุปกรณ์',
    type: 'บุคคลธรรมดา',
    taxId: '1234567890123',
    phones: ['081-234-5678'],
    email: 'somkiat.tool@email.com',
  },
  {
    id: 'SP0003',
    name: 'T-Chemicals Group',
    type: 'นิติบุคคล',
    taxId: '0105559876543',
    contactPerson: 'คุณสุนีย์',
    phones: ['02-111-2222', '02-111-3333'],
    email: 'sunee@t-chemicals.com',
  },
  {
    id: 'SP0004',
    name: 'ร้านป้าจิตร อุปกรณ์เคมี',
    type: 'บุคคลธรรมดา',
    phones: ['088-765-4321'],
    email: 'pa-jit@shop.com',
  },
  {
    id: 'SP0005',
    name: 'บริษัท คลีนโปร จำกัด',
    type: 'นิติบุคคล',
    taxId: '0105551212121',
    contactPerson: 'คุณกิตติ',
    phones: ['02-551-1234'],
    email: 'sales@cleanpro.co.th',
  },
  {
    id: 'SP0006',
    name: 'Green Pest Solutions',
    type: 'นิติบุคคล',
    taxId: '0105553434343',
    contactPerson: 'Ms. Ann',
    phones: ['02-777-8888'],
    email: 'ann@greenpest.sol',
  },
  {
    id: 'SP0007',
    name: 'นายดำรง เคมีภัณฑ์',
    type: 'บุคคลธรรมดา',
    phones: ['089-999-0001'],
  },
];

export const MOCK_WAREHOUSES: Warehouse[] = [
  {
    id: 'wh-1',
    name: 'คลังหลัก',
    location: 'สำนักงานใหญ่',
    type: 'คลัง',
    status: Status.Approved,
    withdrawalLimits: {},
  },
  {
    id: 'wh-2',
    name: 'รถบริการ A',
    location: 'เคลื่อนที่',
    type: 'รถ',
    licensePlate: '1กข 1234',
    brand: 'Toyota',
    model: 'Hilux Revo',
    color: 'ขาว',
    withdrawalLimits: { 'PROD-001': 2 },
  },
  {
    id: 'wh-3',
    name: 'รถบริการ B',
    location: 'เคลื่อนที่',
    type: 'รถ',
    licensePlate: '2กค 5678',
    brand: 'Isuzu',
    model: 'D-Max',
    color: 'บรอนซ์เงิน',
    withdrawalLimits: {},
  },
  {
    id: 'wh-4',
    name: 'คลังย่อย-บางนา',
    location: 'บางนา',
    type: 'คลัง',
    status: Status.Rejected,
    withdrawalLimits: {},
  },
  {
    id: 'wh-5',
    name: 'รถบริการ C',
    location: 'เคลื่อนที่',
    type: 'รถ',
    licensePlate: '3กฆ 9876',
    brand: 'Ford',
    model: 'Ranger',
    color: 'น้ำเงิน',
    withdrawalLimits: {},
  },
  {
    id: 'wh-6',
    name: 'รถบริการ D',
    location: 'เคลื่อนที่',
    type: 'รถ',
    licensePlate: '4กง 5432',
    brand: 'Mitsubishi',
    model: 'Triton',
    color: 'ดำ',
    withdrawalLimits: {},
  },
  {
    id: 'wh-7',
    name: 'รถบริการ E',
    location: 'เคลื่อนที่',
    type: 'รถ',
    licensePlate: '5กจ 1098',
    brand: 'Nissan',
    model: 'Navara',
    color: 'แดง',
    withdrawalLimits: {},
  },
];

// FIX: Added missing mock data definitions and exports
export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'PROD-001',
    name: 'น้ำยา A',
    type: 'สินค้า',
    categoryId: 'CH001',
    unit: 'ลิตร',
    price: 500,
    stock: 100,
    lowStockThreshold: 10,
    warehouse: 'คลังหลัก',
    createdBy: 'แอดมิน',
    updatedBy: 'แอดมิน',
  },
  {
    id: 'PROD-002',
    name: 'เหยื่อ B',
    type: 'สินค้า',
    categoryId: 'CH001',
    unit: 'กล่อง',
    price: 1200,
    stock: 50,
    lowStockThreshold: 5,
    warehouse: 'คลังหลัก',
    createdBy: 'แอดมิน',
    updatedBy: 'แอดมิน',
  },
  {
    id: 'PROD-003',
    name: 'เครื่องพ่น',
    type: 'สินค้า',
    categoryId: 'MAT001',
    unit: 'เครื่อง',
    price: 3500,
    stock: 5,
    lowStockThreshold: 2,
    warehouse: 'คลังหลัก',
    createdBy: 'แอดมิน',
    updatedBy: 'แอดมิน',
  },
  {
    id: 'PK0001',
    name: 'แพ็กเกจกำจัดปลวกรายปี - บ้านเดี่ยว',
    type: 'บริการ',
    categoryId: 'SV001',
    unit: 'แพ็กเกจ',
    price: 8000,
    numberOfVisits: 4,
    contractDuration: '1 ปี',
    stock: 999,
    lowStockThreshold: 0,
    warehouse: 'N/A',
    createdBy: 'แอดมิน',
    updatedBy: 'แอดมิน',
  },
  {
    id: 'PROD-004',
    name: 'น้ำยา C',
    type: 'สินค้า',
    categoryId: 'CH001',
    unit: 'ลิตร',
    price: 650,
    stock: 20,
    lowStockThreshold: 10,
    warehouse: 'คลังย่อย-บางนา',
    createdBy: 'ชาร์ลี',
    updatedBy: 'ชาร์ลี',
  },
  {
    id: 'PROD-005',
    name: 'หน้ากากกรอง',
    type: 'สินค้า',
    categoryId: 'MAT001',
    unit: 'ชิ้น',
    price: 300,
    stock: 15,
    lowStockThreshold: 10,
    warehouse: 'รถบริการ A',
    createdBy: 'ชาร์ลี',
    updatedBy: 'ชาร์ลี',
  },
  {
    id: 'PROD-006',
    name: 'ถุงมือเคมี',
    type: 'สินค้า',
    categoryId: 'MAT001',
    unit: 'คู่',
    price: 200,
    stock: 40,
    lowStockThreshold: 20,
    warehouse: 'คลังหลัก',
    createdBy: 'ชาร์ลี',
    updatedBy: 'ชาร์ลี',
  },
  {
    id: 'PK0002',
    name: 'แพ็กเกจตรวจเช็ครายเดือน',
    type: 'บริการ',
    categoryId: 'SV002',
    unit: 'แพ็กเกจ',
    price: 3000,
    numberOfVisits: 12,
    contractDuration: '1 ปี',
    stock: 999,
    lowStockThreshold: 0,
    warehouse: 'N/A',
    createdBy: 'อลิซ',
    updatedBy: 'อลิซ',
  },
  {
    id: 'PK0003',
    name: 'แพ็กเกจฆ่าเชื้อออฟฟิศ',
    type: 'บริการ',
    categoryId: 'SV002',
    unit: 'แพ็กเกจ',
    price: 5000,
    numberOfVisits: 6,
    contractDuration: '6 เดือน',
    stock: 999,
    lowStockThreshold: 0,
    warehouse: 'N/A',
    createdBy: 'อลิซ',
    updatedBy: 'อลิซ',
  },
];

export const MOCK_ASSESSMENTS: Assessment[] = [
  {
    id: 'asm-001',
    createdAt: '2023-10-01',
    customerId: 'C0002',
    customerName: 'คุณสมชาย L.',
    address: '123 สุขุมวิท',
    subdistrict: 'คลองเตย',
    district: 'คลองเตย',
    province: 'กรุงเทพมหานคร',
    postalCode: '10110',
    scheduledAt: new Date().toISOString(),
    workAreas: [
      {
        id: 'wa-1',
        name: 'ชั้น 1',
        areaSize: 150,
        linearMeters: 0,
        serviceType: ['กำจัดปลวก'],
        estimatedCost: 8000,
        items: [],
      },
    ],
    totalEstimatedCost: 8000,
    status: Status.Completed,
    createdBy: 'อลิซ',
    updatedBy: 'อลิซ',
  },
  {
    id: 'asm-002',
    createdAt: '2023-10-02',
    customerId: 'C0003',
    customerName: 'ร้านกาแฟ Bake a Wish',
    address: 'สยามสแควร์วัน',
    subdistrict: 'ปทุมวัน',
    district: 'ปทุมวัน',
    province: 'กรุงเทพมหานคร',
    postalCode: '10330',
    scheduledAt: '2023-10-28T10:00:00Z',
    workAreas: [
      {
        id: 'wa-2',
        name: 'โซนครัว',
        areaSize: 50,
        linearMeters: 0,
        serviceType: ['กำจัดแมลงสาบ', 'กำจัดหนู'],
        estimatedCost: 2500,
        items: [],
      },
    ],
    totalEstimatedCost: 2500,
    status: Status.Draft,
    createdBy: 'อลิซ',
    updatedBy: 'อลิซ',
  },
  {
    id: 'asm-003',
    createdAt: '2024-01-15',
    customerId: 'C0005',
    customerName: 'บจก. กรีนมาร์ท',
    address: '12/3 พหลโยธิน',
    subdistrict: 'ลาดยาว',
    district: 'จตุจักร',
    province: 'กรุงเทพมหานคร',
    postalCode: '10900',
    scheduledAt: '2024-01-20T09:00:00Z',
    workAreas: [
      {
        id: 'wa-3',
        name: 'คลังสินค้า',
        areaSize: 400,
        linearMeters: 0,
        serviceType: ['กำจัดหนู'],
        estimatedCost: 4500,
        items: [],
      },
    ],
    totalEstimatedCost: 4500,
    status: Status.PendingApproval,
    createdBy: 'อลิซ',
    updatedBy: 'อลิซ',
  },
  {
    id: 'asm-004',
    createdAt: '2024-02-02',
    customerId: 'C0006',
    customerName: 'คอนโด ซิตี้วิว',
    address: '88 เจริญกรุง',
    subdistrict: 'บางรัก',
    district: 'บางรัก',
    province: 'กรุงเทพมหานคร',
    postalCode: '10500',
    scheduledAt: '2024-02-05T13:30:00Z',
    workAreas: [
      {
        id: 'wa-4',
        name: 'พื้นที่ส่วนกลาง',
        areaSize: 600,
        linearMeters: 0,
        serviceType: ['กำจัดปลวก'],
        estimatedCost: 12000,
        items: [],
      },
    ],
    totalEstimatedCost: 12000,
    status: Status.InProgress,
    createdBy: 'อลิซ',
    updatedBy: 'อลิซ',
  },
  {
    id: 'asm-005',
    createdAt: '2024-06-18',
    customerId: 'C0010',
    customerName: 'โรงแรม ซีบรีซ',
    address: '101 เพชรเกษม',
    subdistrict: 'หัวหิน',
    district: 'หัวหิน',
    province: 'ประจวบคีรีขันธ์',
    postalCode: '77110',
    scheduledAt: new Date(
      new Date().getTime() + 2 * 24 * 60 * 60 * 1000
    ).toISOString(),
    workAreas: [
      {
        id: 'wa-5',
        name: 'ชั้น 3',
        areaSize: 300,
        linearMeters: 0,
        serviceType: ['กำจัดยุง', 'กำจัดแมลงสาบ'],
        estimatedCost: 9000,
        items: [],
      },
    ],
    totalEstimatedCost: 9000,
    status: Status.Completed,
    createdBy: 'อลิซ',
    updatedBy: 'อลิซ',
  },
  {
    id: 'asm-006',
    createdAt: '2024-08-02',
    customerId: 'C0004',
    customerName: 'คุณพลอย P.',
    address: '456 ลาดพร้าว',
    subdistrict: 'จตุจักร',
    district: 'จตุจักร',
    province: 'กรุงเทพมหานคร',
    postalCode: '10900',
    scheduledAt: new Date(
      new Date().getTime() + 4 * 24 * 60 * 60 * 1000
    ).toISOString(),
    workAreas: [
      {
        id: 'wa-6',
        name: 'บ้านทั้งหลัง',
        areaSize: 180,
        linearMeters: 0,
        serviceType: ['กำจัดปลวก'],
        estimatedCost: 8000,
        items: [],
      },
    ],
    totalEstimatedCost: 8000,
    status: Status.Draft,
    createdBy: 'อลิซ',
    updatedBy: 'อลิซ',
  },
  {
    id: 'asm-007',
    createdAt: '2024-07-10',
    customerId: 'C0003',
    customerName: 'ร้านกาแฟ Bake a Wish',
    address: 'สยามสแควร์วัน',
    subdistrict: 'ปทุมวัน',
    district: 'ปทุมวัน',
    province: 'กรุงเทพมหานคร',
    postalCode: '10330',
    scheduledAt: new Date(
      new Date().getTime() + 7 * 24 * 60 * 60 * 1000
    ).toISOString(),
    workAreas: [
      {
        id: 'wa-7',
        name: 'โซนหน้าเคาน์เตอร์',
        areaSize: 40,
        linearMeters: 0,
        serviceType: ['กำจัดแมลงสาบ'],
        estimatedCost: 3000,
        items: [],
      },
    ],
    totalEstimatedCost: 3000,
    status: Status.Draft,
    createdBy: 'อลิซ',
    updatedBy: 'อลิซ',
  },
  {
    id: 'asm-008',
    createdAt: '2024-02-10',
    customerId: 'C0006',
    customerName: 'คอนโด ซิตี้วิว',
    address: '88 เจริญกรุง',
    subdistrict: 'บางรัก',
    district: 'บางรัก',
    province: 'กรุงเทพมหานคร',
    postalCode: '10500',
    scheduledAt: new Date(
      new Date().getTime() + 9 * 24 * 60 * 60 * 1000
    ).toISOString(),
    workAreas: [
      {
        id: 'wa-8',
        name: 'ดาดฟ้า',
        areaSize: 500,
        linearMeters: 0,
        serviceType: ['กำจัดยุง'],
        estimatedCost: 12000,
        items: [],
      },
    ],
    totalEstimatedCost: 12000,
    status: Status.Draft,
    createdBy: 'อลิซ',
    updatedBy: 'อลิซ',
  },
  {
    id: 'asm-009',
    createdAt: '2024-09-01',
    customerId: 'C0008',
    customerName: 'ร้าน The Coffee Hub',
    address: '15 ศรีนครินทร์',
    subdistrict: 'บางแก้ว',
    district: 'บางพลี',
    province: 'สมุทรปราการ',
    postalCode: '10540',
    scheduledAt: '2024-09-05T10:00:00Z',
    workAreas: [
      {
        id: 'wa-9',
        name: 'ทั้งร้าน',
        areaSize: 80,
        linearMeters: 0,
        serviceType: ['กำจัดแมลงสาบ', 'กำจัดมด'],
        estimatedCost: 6000,
        items: [],
      },
    ],
    totalEstimatedCost: 6000,
    status: Status.Completed,
    createdBy: 'อลิซ',
    updatedBy: 'อลิซ',
  },
  {
    id: 'asm-010',
    createdAt: '2024-09-10',
    customerId: 'C0009',
    customerName: 'คุณมินตรา M.',
    address: '45/6 นิมมานเหมินทร์',
    subdistrict: 'สุเทพ',
    district: 'เมืองเชียงใหม่',
    province: 'เชียงใหม่',
    postalCode: '50200',
    scheduledAt: '2024-09-15T13:00:00Z',
    workAreas: [
      {
        id: 'wa-10',
        name: 'บ้านพัก',
        areaSize: 120,
        linearMeters: 0,
        serviceType: ['กำจัดปลวก'],
        estimatedCost: 15000,
        items: [],
      },
    ],
    totalEstimatedCost: 15000,
    status: Status.Completed,
    createdBy: 'อลิซ',
    updatedBy: 'อลิซ',
  },
  {
    id: 'asm-011',
    createdAt: '2024-10-01',
    customerId: 'C0001',
    customerName: 'ห้างแกรนด์เซ็นทรัล',
    address: '999 พระราม 1',
    subdistrict: 'ปทุมวัน',
    district: 'ปทุมวัน',
    province: 'กรุงเทพมหานคร',
    postalCode: '10330',
    scheduledAt: '2024-10-05T09:00:00Z',
    workAreas: [
      {
        id: 'wa-11',
        name: 'Food Court',
        areaSize: 1000,
        linearMeters: 0,
        serviceType: ['กำจัดหนู', 'กำจัดแมลงสาบ'],
        estimatedCost: 35000,
        items: [],
      },
    ],
    totalEstimatedCost: 35000,
    status: Status.Completed,
    createdBy: 'อลิซ',
    updatedBy: 'อลิซ',
  },
  {
    id: 'asm-012',
    createdAt: '2024-11-05',
    customerId: 'C0007',
    customerName: 'คุณดล D.',
    address: '99/1 กาญจนาภิเษก',
    subdistrict: 'บางแค',
    district: 'บางแค',
    province: 'กรุงเทพมหานคร',
    postalCode: '10160',
    scheduledAt: '2024-11-10T11:00:00Z',
    workAreas: [
      {
        id: 'wa-12',
        name: 'สวนรอบบ้าน',
        areaSize: 200,
        linearMeters: 0,
        serviceType: ['กำจัดยุง'],
        estimatedCost: 4000,
        items: [],
      },
    ],
    totalEstimatedCost: 4000,
    status: Status.PendingApproval,
    createdBy: 'อลิซ',
    updatedBy: 'อลิซ',
  },
  {
    id: 'asm-013',
    createdAt: '2024-11-15',
    customerId: 'C0002',
    customerName: 'คุณสมชาย L.',
    address: '123 สุขุมวิท',
    subdistrict: 'คลองเตย',
    district: 'คลองเตย',
    province: 'กรุงเทพมหานคร',
    postalCode: '10110',
    scheduledAt: '2024-11-20T14:00:00Z',
    workAreas: [
      {
        id: 'wa-13',
        name: 'โรงรถ',
        areaSize: 30,
        linearMeters: 0,
        serviceType: ['กำจัดมด'],
        estimatedCost: 2000,
        items: [],
      },
    ],
    totalEstimatedCost: 2000,
    status: Status.Draft,
    createdBy: 'อลิซ',
    updatedBy: 'อลิซ',
  },
];

export const MOCK_FIELD_JOBS: FieldJob[] = [
  {
    id: 'SER23001',
    customerId: 'C0001',
    customerName: 'ห้างแกรนด์เซ็นทรัล',
    address: '999 พระราม 1',
    startTime: new Date().toISOString(),
    endTime: new Date(new Date().getTime() + 2 * 60 * 60 * 1000).toISOString(),
    technicians: [MOCK_USERS[0], MOCK_USERS[5]],
    workAreas: [
      { id: 'fjwa-1', name: 'ชั้น G', servicePackage: 'ตรวจเช็คประจำเดือน' },
    ],
    status: Status.Planned,
    vehicleId: 'wh-2',
  },
  {
    id: 'SER23002',
    customerId: 'C0002',
    customerName: 'คุณสมชาย L.',
    address: '123 สุขุมวิท',
    startTime: '2023-10-28T14:00:00Z',
    endTime: '2023-10-28T16:00:00Z',
    technicians: [MOCK_USERS[6]],
    workAreas: [
      {
        id: 'fjwa-2',
        name: 'บ้านทั้งหลัง',
        servicePackage: 'แพ็กเกจกำจัดปลวกรายปี',
      },
    ],
    status: Status.Completed,
    vehicleId: 'wh-3',
    serviceReport: {
      createdAt: '2023-10-28',
      checkInTime: '14:05',
      checkOutTime: '15:50',
      serviceTypes: ['กำจัดปลวก'],
      serviceActions: ['เติมเหยื่อ'],
      status: Status.Completed,
    },
  },
  {
    id: 'SER24001',
    customerId: 'C0005',
    customerName: 'บจก. กรีนมาร์ท',
    address: '12/3 พหลโยธิน',
    startTime: new Date(
      new Date().getTime() + 3 * 24 * 60 * 60 * 1000
    ).toISOString(),
    endTime: new Date(
      new Date().getTime() + 3 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000
    ).toISOString(),
    technicians: [MOCK_USERS[5]],
    workAreas: [
      { id: 'fjwa-3', name: 'คลังสินค้า', servicePackage: 'กำจัดหนู' },
    ],
    status: Status.Planned,
    vehicleId: 'wh-2',
  },
  {
    id: 'SER24002',
    customerId: 'C0008',
    customerName: 'ร้าน The Coffee Hub',
    address: '15 ศรีนครินทร์',
    startTime: new Date(
      new Date().getTime() + 5 * 24 * 60 * 60 * 1000
    ).toISOString(),
    endTime: new Date(
      new Date().getTime() + 5 * 24 * 60 * 60 * 1000 + 60 * 60 * 1000
    ).toISOString(),
    technicians: [MOCK_USERS[7]],
    workAreas: [
      { id: 'fjwa-4', name: 'โซนเสิร์ฟ', servicePackage: 'กำจัดแมลงสาบ' },
    ],
    status: Status.Planned,
    vehicleId: 'wh-3',
  },
  {
    id: 'SER24003',
    contractId: 'CON-3',
    customerId: 'C0010',
    customerName: 'โรงแรม ซีบรีซ',
    address: '101 เพชรเกษม',
    startTime: new Date(
      new Date().getTime() + 2 * 24 * 60 * 60 * 1000
    ).toISOString(),
    endTime: new Date(
      new Date().getTime() + 2 * 24 * 60 * 60 * 1000 + 90 * 60 * 1000
    ).toISOString(),
    technicians: [MOCK_USERS[0], MOCK_USERS[8]],
    workAreas: [
      { id: 'fjwa-5', name: 'ชั้น 3', servicePackage: 'แพ็กเกจฆ่าเชื้อออฟฟิศ' },
    ],
    status: Status.Scheduled,
    vehicleId: 'wh-5',
  },
  {
    id: 'SER24004',
    contractId: 'CON-4',
    customerId: 'C0003',
    customerName: 'ร้านกาแฟ Bake a Wish',
    address: 'สยามสแควร์วัน',
    startTime: new Date(
      new Date().getTime() + 6 * 24 * 60 * 60 * 1000
    ).toISOString(),
    endTime: new Date(
      new Date().getTime() + 6 * 24 * 60 * 60 * 1000 + 60 * 60 * 1000
    ).toISOString(),
    technicians: [MOCK_USERS[7]],
    workAreas: [
      {
        id: 'fjwa-6',
        name: 'โซนหน้าเคาน์เตอร์',
        servicePackage: 'แพ็กเกจตรวจเช็ครายเดือน',
      },
    ],
    status: Status.Scheduled,
    vehicleId: 'wh-3',
  },
  {
    id: 'SER24005',
    contractId: 'CON-4',
    customerId: 'C0003',
    customerName: 'ร้านกาแฟ Bake a Wish',
    address: 'สยามสแควร์วัน',
    startTime: new Date(
      new Date().getTime() - 20 * 24 * 60 * 60 * 1000
    ).toISOString(),
    endTime: new Date(
      new Date().getTime() - 20 * 24 * 60 * 60 * 1000 + 60 * 60 * 1000
    ).toISOString(),
    technicians: [MOCK_USERS[9]],
    workAreas: [
      {
        id: 'fjwa-7',
        name: 'โซนครัว',
        servicePackage: 'แพ็กเกจตรวจเช็ครายเดือน',
      },
    ],
    status: Status.Completed,
    vehicleId: 'wh-2',
    serviceReport: {
      createdAt: new Date(
        new Date().getTime() - 20 * 24 * 60 * 60 * 1000
      ).toISOString(),
      checkInTime: '10:00',
      checkOutTime: '11:00',
      serviceTypes: ['กำจัดแมลงสาบ'],
      serviceActions: ['ตรวจเช็ค'],
      status: Status.Completed,
    },
  },
  {
    id: 'SER24006',
    contractId: 'CON-5',
    customerId: 'C0004',
    customerName: 'คุณพลอย P.',
    address: '456 ลาดพร้าว',
    startTime: new Date(
      new Date().getTime() + 8 * 24 * 60 * 60 * 1000
    ).toISOString(),
    endTime: new Date(
      new Date().getTime() + 8 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000
    ).toISOString(),
    technicians: [MOCK_USERS[10]],
    workAreas: [
      {
        id: 'fjwa-8',
        name: 'บ้านทั้งหลัง',
        servicePackage: 'แพ็กเกจกำจัดปลวกรายปี - บ้านเดี่ยว',
      },
    ],
    status: Status.Planned,
    vehicleId: 'wh-6',
  },
  {
    id: 'SER24007',
    customerId: 'C0006',
    customerName: 'คอนโด ซิตี้วิว',
    address: '88 เจริญกรุง',
    startTime: new Date(
      new Date().getTime() + 1 * 24 * 60 * 60 * 1000
    ).toISOString(),
    endTime: new Date(
      new Date().getTime() + 1 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000
    ).toISOString(),
    technicians: [MOCK_USERS[5], MOCK_USERS[6]],
    workAreas: [
      { id: 'fjwa-9', name: 'พื้นที่ส่วนกลาง', servicePackage: 'กำจัดปลวก' },
    ],
    status: Status.InProgress,
    vehicleId: 'wh-2',
  },
  {
    id: 'SER24008',
    customerId: 'C0001',
    customerName: 'ห้างแกรนด์เซ็นทรัล',
    address: '999 พระราม 1',
    startTime: new Date(
      new Date().getTime() + 12 * 24 * 60 * 60 * 1000
    ).toISOString(),
    endTime: new Date(
      new Date().getTime() + 12 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000
    ).toISOString(),
    technicians: [MOCK_USERS[11], MOCK_USERS[12]],
    workAreas: [
      { id: 'fjwa-10', name: 'ชั้น G', servicePackage: 'ตรวจเช็คประจำเดือน' },
    ],
    status: Status.Planned,
    vehicleId: 'wh-7',
  },
  {
    id: 'SER24009',
    contractId: 'CON-6',
    customerId: 'C0008',
    customerName: 'ร้าน The Coffee Hub',
    address: '15 ศรีนครินทร์',
    startTime: '2024-09-12T10:00:00Z',
    endTime: '2024-09-12T12:00:00Z',
    technicians: [MOCK_USERS[8]],
    workAreas: [
      { id: 'fjwa-11', name: 'ทั้งร้าน', servicePackage: 'Premium Care' },
    ],
    status: Status.Completed,
    vehicleId: 'wh-3',
    serviceReport: {
      createdAt: '2024-09-12',
      checkInTime: '10:05',
      checkOutTime: '11:55',
      serviceTypes: ['กำจัดแมลงสาบ'],
      serviceActions: ['พ่นสเปรย์'],
      status: Status.Completed,
    },
  },
  {
    id: 'SER24010',
    contractId: 'CON-6',
    customerId: 'C0008',
    customerName: 'ร้าน The Coffee Hub',
    address: '15 ศรีนครินทร์',
    startTime: new Date(
      new Date().getTime() - 2 * 24 * 60 * 60 * 1000
    ).toISOString(),
    endTime: new Date(
      new Date().getTime() - 2 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000
    ).toISOString(),
    technicians: [MOCK_USERS[8]],
    workAreas: [
      { id: 'fjwa-12', name: 'ทั้งร้าน', servicePackage: 'Premium Care' },
    ],
    status: Status.Completed,
    vehicleId: 'wh-3',
  },
  {
    id: 'SER24011',
    contractId: 'CON-7',
    customerId: 'C0001',
    customerName: 'ห้างแกรนด์เซ็นทรัล',
    address: '999 พระราม 1',
    startTime: '2024-10-16T22:00:00Z',
    endTime: '2024-10-17T02:00:00Z',
    technicians: [MOCK_USERS[11], MOCK_USERS[12], MOCK_USERS[13]],
    workAreas: [
      {
        id: 'fjwa-13',
        name: 'Food Court',
        servicePackage: 'Commercial Pest Control',
      },
    ],
    status: Status.Completed,
    vehicleId: 'wh-7',
  },
  {
    id: 'SER24012',
    contractId: 'CON-7',
    customerId: 'C0001',
    customerName: 'ห้างแกรนด์เซ็นทรัล',
    address: '999 พระราม 1',
    startTime: new Date(
      new Date().getTime() + 10 * 24 * 60 * 60 * 1000
    ).toISOString(),
    endTime: new Date(
      new Date().getTime() + 10 * 24 * 60 * 60 * 1000 + 4 * 60 * 60 * 1000
    ).toISOString(),
    technicians: [MOCK_USERS[11], MOCK_USERS[12]],
    workAreas: [
      {
        id: 'fjwa-14',
        name: 'Food Court',
        servicePackage: 'Commercial Pest Control',
      },
    ],
    status: Status.Planned,
    vehicleId: 'wh-7',
  },
  {
    id: 'SER24013',
    customerId: 'C0002',
    customerName: 'คุณสมชาย L.',
    address: '123 สุขุมวิท',
    startTime: new Date(
      new Date().getTime() + 1 * 24 * 60 * 60 * 1000
    ).toISOString(),
    endTime: new Date(
      new Date().getTime() + 1 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000
    ).toISOString(),
    technicians: [MOCK_USERS[0]],
    workAreas: [
      { id: 'fjwa-15', name: 'โรงรถ', servicePackage: 'One-time Service' },
    ],
    status: Status.Scheduled,
    vehicleId: 'wh-2',
  },
];

export const MOCK_QUOTATIONS: Quotation[] = [
  {
    id: 'QT660001-1',
    assessmentId: 'asm-001',
    customerId: 'C0002',
    customerName: 'คุณสมชาย L.',
    createdAt: '2023-10-03',
    expiresAt: '2023-11-02',
    status: Status.Converted,
    total: 8000,
    revision: 1,
  },
  {
    id: 'QT670001-1',
    assessmentId: 'asm-003',
    customerId: 'C0005',
    customerName: 'บจก. กรีนมาร์ท',
    createdAt: '2024-01-17',
    expiresAt: '2024-02-16',
    status: Status.Sent,
    total: 4500,
    revision: 1,
  },
  {
    id: 'QT670002-1',
    assessmentId: 'asm-005',
    customerId: 'C0010',
    customerName: 'โรงแรม ซีบรีซ',
    createdAt: '2024-06-18',
    expiresAt: '2024-07-18',
    status: Status.Sent,
    total: 9000,
    revision: 1,
  },
  {
    id: 'QT670003-1',
    assessmentId: 'asm-007',
    customerId: 'C0003',
    customerName: 'ร้านกาแฟ Bake a Wish',
    createdAt: '2024-07-10',
    expiresAt: '2024-08-09',
    status: Status.Sent,
    total: 5500,
    revision: 1,
  },
  {
    id: 'QT670004-1',
    assessmentId: 'asm-006',
    customerId: 'C0004',
    customerName: 'คุณพลอย P.',
    createdAt: '2024-08-02',
    expiresAt: '2024-09-01',
    status: Status.Sent,
    total: 8000,
    revision: 1,
  },
  {
    id: 'QT670005-1',
    assessmentId: 'asm-009',
    customerId: 'C0008',
    customerName: 'ร้าน The Coffee Hub',
    createdAt: '2024-09-06',
    expiresAt: '2024-10-06',
    status: Status.Converted,
    total: 6000,
    revision: 1,
  },
  {
    id: 'QT670006-1',
    assessmentId: 'asm-010',
    customerId: 'C0009',
    customerName: 'คุณมินตรา M.',
    createdAt: '2024-09-16',
    expiresAt: '2024-10-16',
    status: Status.Sent,
    total: 15000,
    revision: 1,
  },
  {
    id: 'QT670007-1',
    assessmentId: 'asm-011',
    customerId: 'C0001',
    customerName: 'ห้างแกรนด์เซ็นทรัล',
    createdAt: '2024-10-06',
    expiresAt: '2024-11-05',
    status: Status.Converted,
    total: 35000,
    revision: 1,
  },
  {
    id: 'QT670008-1',
    assessmentId: 'asm-012',
    customerId: 'C0007',
    customerName: 'คุณดล D.',
    createdAt: '2024-11-12',
    expiresAt: '2024-12-12',
    status: Status.Draft,
    total: 4000,
    revision: 1,
  },
];

export const MOCK_CONTRACTS: Contract[] = [
  {
    id: 'CON-1',
    customerId: 'C0002',
    customerName: 'คุณสมชาย L.',
    quotationId: 'QT660001-1',
    address: '123 สุขุมวิท',
    startDate: '2023-10-05',
    endDate: '2024-10-04',
    servicePackage: 'แพ็กเกจกำจัดปลวกรายปี',
    status: Status.InProgress,
    totalAmount: 8000,
  },
  {
    id: 'CON-2',
    customerId: 'C0005',
    customerName: 'บจก. กรีนมาร์ท',
    quotationId: 'QT670001-1',
    address: '12/3 พหลโยธิน',
    startDate: '2024-01-25',
    endDate: '2024-07-25',
    servicePackage: 'กำจัดหนู',
    status: Status.InProgress,
    totalAmount: 4500,
  },
  {
    id: 'CON-3',
    customerId: 'C0010',
    customerName: 'โรงแรม ซีบรีซ',
    quotationId: 'QT670002-1',
    address: '101 เพชรเกษม',
    startDate: '2024-06-20',
    endDate: '2024-12-19',
    servicePackage: 'แพ็กเกจฆ่าเชื้อออฟฟิศ',
    status: Status.InProgress,
    totalAmount: 9000,
  },
  {
    id: 'CON-4',
    customerId: 'C0003',
    customerName: 'ร้านกาแฟ Bake a Wish',
    quotationId: 'QT670003-1',
    address: 'สยามสแควร์วัน',
    startDate: '2024-07-15',
    endDate: '2025-07-14',
    servicePackage: 'แพ็กเกจตรวจเช็ครายเดือน',
    status: Status.InProgress,
    totalAmount: 5500,
  },
  {
    id: 'CON-5',
    customerId: 'C0004',
    customerName: 'คุณพลอย P.',
    quotationId: 'QT670004-1',
    address: '456 ลาดพร้าว',
    startDate: '2024-08-05',
    endDate: '2025-08-04',
    servicePackage: 'แพ็กเกจกำจัดปลวกรายปี - บ้านเดี่ยว',
    status: Status.InProgress,
    totalAmount: 12000,
  },
  {
    id: 'CON-6',
    customerId: 'C0008',
    customerName: 'ร้าน The Coffee Hub',
    quotationId: 'QT670005-1',
    address: '15 ศรีนครินทร์',
    startDate: '2024-09-10',
    endDate: '2025-09-09',
    servicePackage: 'Premium Care รายปี',
    status: Status.InProgress,
    totalAmount: 6000,
  },
  {
    id: 'CON-7',
    customerId: 'C0001',
    customerName: 'ห้างแกรนด์เซ็นทรัล',
    quotationId: 'QT670007-1',
    address: '999 พระราม 1',
    startDate: '2024-10-15',
    endDate: '2025-10-14',
    servicePackage: 'Commercial Pest Control',
    status: Status.InProgress,
    totalAmount: 35000,
  },
];

export const MOCK_INVOICES: Invoice[] = [
  {
    id: 'inv-001',
    quotationId: 'QT660001-1',
    customerId: 'C0002',
    customerName: 'คุณสมชาย L.',
    issuedAt: '2023-10-05',
    dueAt: '2023-11-04',
    status: Status.Paid,
    total: 8000,
  },
  {
    id: 'inv-002',
    customerId: 'C0001',
    customerName: 'ห้างแกรนด์เซ็นทรัล',
    issuedAt: '2023-09-01',
    dueAt: '2023-10-01',
    status: Status.Overdue,
    total: 15000,
  },
  {
    id: 'inv-003',
    customerId: 'C0005',
    customerName: 'บจก. กรีนมาร์ท',
    issuedAt: '2024-01-25',
    dueAt: '2024-02-24',
    status: Status.Sent,
    total: 4500,
  },
  {
    id: 'inv-004',
    customerId: 'C0006',
    customerName: 'คอนโด ซิตี้วิว',
    issuedAt: '2024-02-06',
    dueAt: '2024-03-07',
    status: Status.Paid,
    total: 12000,
  },
  {
    id: 'inv-005',
    customerId: 'C0008',
    customerName: 'ร้าน The Coffee Hub',
    issuedAt: '2024-04-05',
    dueAt: '2024-05-05',
    status: Status.Paid,
    total: 3000,
  },
  {
    id: 'inv-006',
    customerId: 'C0009',
    customerName: 'คุณมินตรา M.',
    issuedAt: '2024-05-10',
    dueAt: '2024-06-09',
    status: Status.Paid,
    total: 2500,
  },
  {
    id: 'inv-007',
    customerId: 'C0010',
    customerName: 'โรงแรม ซีบรีซ',
    issuedAt: '2024-06-16',
    dueAt: '2024-07-16',
    status: Status.Sent,
    total: 9000,
  },
  {
    id: 'inv-008',
    customerId: 'C0003',
    customerName: 'ร้านกาแฟ Bake a Wish',
    issuedAt: '2024-07-02',
    dueAt: '2024-08-01',
    status: Status.Overdue,
    total: 5500,
  },
  {
    id: 'inv-009',
    quotationId: 'QT670005-1',
    customerId: 'C0008',
    customerName: 'ร้าน The Coffee Hub',
    issuedAt: '2024-09-07',
    dueAt: '2024-10-07',
    status: Status.Paid,
    total: 6000,
  },
  {
    id: 'inv-010',
    quotationId: 'QT670007-1',
    customerId: 'C0001',
    customerName: 'ห้างแกรนด์เซ็นทรัล',
    issuedAt: '2024-10-07',
    dueAt: '2024-11-06',
    status: Status.Paid,
    total: 35000,
  },
  {
    id: 'inv-011',
    quotationId: 'QT670006-1',
    customerId: 'C0009',
    customerName: 'คุณมินตรา M.',
    issuedAt: '2024-09-17',
    dueAt: '2024-10-17',
    status: Status.Sent,
    total: 15000,
  },
  {
    id: 'inv-012',
    customerId: 'C0004',
    customerName: 'คุณพลอย P.',
    issuedAt: '2024-11-01',
    dueAt: '2024-12-01',
    status: Status.Overdue,
    total: 8000,
  },
  {
    id: 'inv-013',
    customerId: 'C0001',
    customerName: 'ห้างแกรนด์เซ็นทรัล',
    issuedAt: '2024-11-01',
    dueAt: '2024-12-01',
    status: Status.Sent,
    total: 5000,
  },
];

export const MOCK_RECEIPTS: Receipt[] = [
  {
    id: 'rec-001',
    invoiceId: 'inv-001',
    customerId: 'C0002',
    customerName: 'คุณสมชาย L.',
    paidAt: '2023-10-10',
    amount: 8000,
    paymentMethod: 'โอนเงิน',
  },
  {
    id: 'rec-002',
    invoiceId: 'inv-004',
    customerId: 'C0006',
    customerName: 'คอนโด ซิตี้วิว',
    paidAt: '2024-02-12',
    amount: 12000,
    paymentMethod: 'โอนเงิน',
  },
  {
    id: 'rec-003',
    invoiceId: 'inv-005',
    customerId: 'C0008',
    customerName: 'ร้าน The Coffee Hub',
    paidAt: '2024-04-10',
    amount: 3000,
    paymentMethod: 'เงินสด',
  },
  {
    id: 'rec-004',
    invoiceId: 'inv-006',
    customerId: 'C0009',
    customerName: 'คุณมินตรา M.',
    paidAt: '2024-05-15',
    amount: 2500,
    paymentMethod: 'บัตรเครดิต',
  },
];

export const MOCK_GOODS_RECEIPTS: GoodsReceipt[] = [
  {
    id: 'GR670001',
    warehouseId: 'wh-1',
    status: Status.Approved,
    createdAt: '2023-09-20T10:00:00.000Z',
    createdBy: 'ชาร์ลี',
    updatedBy: 'ชาร์ลี',
    approvedBy: 'แอดมิน',
    items: [{ productId: 'PROD-001', quantity: 50 }],
    supplierId: 'SP0001',
  },
  {
    id: 'GR670002',
    warehouseId: 'wh-4',
    status: Status.PendingApproval,
    createdAt: '2024-01-05T10:30:00.000Z',
    createdBy: 'ชาร์ลี',
    updatedBy: 'ชาร์ลี',
    items: [{ productId: 'PROD-004', quantity: 20 }],
    supplierId: 'SP0005',
  },
  {
    id: 'GR670003',
    warehouseId: 'wh-1',
    status: Status.Approved,
    createdAt: '2024-03-11T09:10:00.000Z',
    createdBy: 'ชาร์ลี',
    updatedBy: 'ชาร์ลี',
    approvedBy: 'แอดมิน',
    items: [{ productId: 'PROD-006', quantity: 50 }],
    supplierId: 'SP0006',
  },
];

export const MOCK_WITHDRAWALS: Withdrawal[] = [
  {
    id: 'SR670001',
    createdAt: '2023-09-22T09:00:00.000Z',
    fromWarehouseId: 'wh-1',
    toWarehouseId: 'wh-2',
    status: Status.Approved,
    createdBy: 'อดัม',
    approvedBy: 'แอดมิน',
    items: [{ productId: 'PROD-002', quantity: 2 }],
    expenses: [
      { id: 'exp-1', description: 'ค่าทางด่วน', amount: 120 },
      { id: 'exp-2', description: 'ค่าน้ำมัน', amount: 300 },
    ],
    recipientId: 'user-1',
  },
  {
    id: 'SR670002',
    createdAt: '2024-01-20T08:30:00.000Z',
    fromWarehouseId: 'wh-1',
    toWarehouseId: 'wh-2',
    status: Status.Approved,
    createdBy: 'อดัม',
    approvedBy: 'แอดมิน',
    items: [{ productId: 'PROD-001', quantity: 5 }],
    expenses: [{ id: 'exp-3', description: 'ค่าทางด่วน', amount: 60 }],
    recipientId: 'user-6',
  },
  {
    id: 'SR670003',
    createdAt: '2024-02-05T11:00:00.000Z',
    fromWarehouseId: 'wh-4',
    toWarehouseId: 'wh-3',
    status: Status.Approved,
    createdBy: 'ชาร์ลี',
    approvedBy: 'แอดมิน',
    items: [{ productId: 'PROD-004', quantity: 4 }],
    expenses: [],
    recipientId: 'user-7',
  },
];

export const MOCK_TRANSFERS: Transfer[] = [
  {
    id: 'IT670001',
    createdAt: '2023-09-25T11:00:00.000Z',
    fromWarehouseId: 'wh-2',
    toWarehouseId: 'wh-3',
    reason: 'รถ B ของหมด',
    createdBy: 'อดัม',
    items: [{ productId: 'PROD-002', quantity: 1 }],
    status: Status.Completed,
  },
  {
    id: 'IT670002',
    createdAt: '2024-03-02T13:15:00.000Z',
    fromWarehouseId: 'wh-3',
    toWarehouseId: 'wh-2',
    reason: 'สลับสินค้า',
    createdBy: 'อดัม',
    items: [{ productId: 'PROD-005', quantity: 2 }],
    status: Status.Completed,
  },
];

export const MOCK_STOCK_ADJUSTMENTS: StockAdjustment[] = [
  {
    id: 'SA670001',
    createdAt: '2023-09-28T16:00:00.000Z',
    warehouseId: 'wh-1',
    reason: 'นับสต็อกผิดพลาด',
    createdBy: 'ชาร์ลี',
    items: [
      {
        productId: 'PROD-001',
        originalQuantity: 100,
        adjustedQuantity: 99,
        reason: 'ทำหก 1 ลิตร',
      },
    ],
    status: Status.Completed,
  },
  {
    id: 'SA670002',
    createdAt: '2024-04-01T10:00:00.000Z',
    warehouseId: 'wh-1',
    reason: 'สต็อกย้ายชั้นวาง',
    createdBy: 'ชาร์ลี',
    items: [
      {
        productId: 'PROD-006',
        originalQuantity: 50,
        adjustedQuantity: 48,
        reason: 'เสียหาย 2 คู่',
      },
    ],
    status: Status.Completed,
  },
];

export const MOCK_PRODUCT_RETURNS: ProductReturn[] = [
  {
    id: 'RT670001',
    createdAt: '2023-09-30T17:00:00.000Z',
    fromWarehouseId: 'wh-2',
    toWarehouseId: 'wh-1',
    createdBy: 'อดัม',
    items: [{ productId: 'PROD-002', quantity: 1, reason: 'ลูกค้าเลื่อนนัด' }],
    status: Status.Completed,
    withdrawalRefId: 'SR670001',
  },
  {
    id: 'RT670002',
    createdAt: '2024-02-20T17:15:00.000Z',
    fromWarehouseId: 'wh-2',
    toWarehouseId: 'wh-1',
    createdBy: 'อดัม',
    items: [{ productId: 'PROD-001', quantity: 2, reason: 'เปลี่ยนแผนงาน' }],
    status: Status.Completed,
  },
];

export const MOCK_RETURN_TO_SUPPLIERS: ReturnToSupplier[] = [
  {
    id: 'RTS670001',
    createdAt: '2023-10-05T10:00:00.000Z',
    warehouseId: 'wh-1',
    supplierId: 'SP0001',
    createdBy: 'ชาร์ลี',
    updatedBy: 'ชาร์ลี',
    items: [{ productId: 'PROD-001', quantity: 5, reason: 'สินค้าเสียหาย' }],
    status: Status.Approved,
    approvedBy: 'แอดมิน',
    referenceId: 'GR670001',
  },
];
