export enum QuotationStatus {
  DRAFT = 'DRAFT',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED = 'APPROVED',
  SIGNED = 'SIGNED',
  PENDING_SIGNATURE = 'PENDING_SIGNATURE',
  FOLLOW_UP = 'FOLLOW_UP',
  CANCELLED = 'CANCELLED',
  REVISE = 'REVISE',
  EXPIRED = 'EXPIRED',
}